server.address=:10001
server.port=8091
request.path=/api


# sqlconn = tbk_2026:tbkA4622511z3!@tcp(rm-1udlgbce4t64wmpdl9o.mysql.rds.aliyuncs.com:3306)/indo_whatsapp?charset=utf8&parseTime=True&loc=Local

log.dir=./logs/

# redis.addr = r-1udr0cqum8k2jguku3pd.redis.rds.aliyuncs.com:6379
# redis.password = tbkA4622511z3!
# redis.mode = standalone

redis.addr = 172.16.49.81:6385
redis.password =
redis.mode = cluster

auth.default_username = admin
auth.default_display_name = Administrator
auth.default_password = admin123
auth.token_ttl_seconds = 604800
auth.token_secret = change-this-development-token-secret
auth.service_token = local-service-token


